//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probadesyat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вход гостя.
    /// </summary>
    // *** Start programmer edit section *** (ВходГостя CustomAttributes)

    // *** End programmer edit section *** (ВходГостя CustomAttributes)
    [AutoAltered()]
    [Caption("Вход гостя")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВходГостяE", new string[] {
            "Гость as \'Гость\'",
            "Гость.ФИО as \'ФИО\'",
            "Гость.Карта.КодКарты as \'Номер карты\'"}, Hidden=new string[] {
            "Гость.ФИО"})]
    [MasterViewDefineAttribute("ВходГостяE", "Гость", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    public class ВходГостя : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Probadesyat.Гость fГость;
        
        private IIS.Probadesyat.РегистрВхода fРегистрВхода;
        
        // *** Start programmer edit section *** (ВходГостя CustomMembers)

        // *** End programmer edit section *** (ВходГостя CustomMembers)

        
        /// <summary>
        /// Вход гостя.
        /// </summary>
        // *** Start programmer edit section *** (ВходГостя.Гость CustomAttributes)

        // *** End programmer edit section *** (ВходГостя.Гость CustomAttributes)
        [PropertyStorage(new string[] {
                "Гость"})]
        [NotNull()]
        public virtual IIS.Probadesyat.Гость Гость
        {
            get
            {
                // *** Start programmer edit section *** (ВходГостя.Гость Get start)

                // *** End programmer edit section *** (ВходГостя.Гость Get start)
                IIS.Probadesyat.Гость result = this.fГость;
                // *** Start programmer edit section *** (ВходГостя.Гость Get end)

                // *** End programmer edit section *** (ВходГостя.Гость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВходГостя.Гость Set start)

                // *** End programmer edit section *** (ВходГостя.Гость Set start)
                this.fГость = value;
                // *** Start programmer edit section *** (ВходГостя.Гость Set end)

                // *** End programmer edit section *** (ВходГостя.Гость Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Probadesyat.РегистрВхода.
        /// </summary>
        // *** Start programmer edit section *** (ВходГостя.РегистрВхода CustomAttributes)

        // *** End programmer edit section *** (ВходГостя.РегистрВхода CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "РегистрВхода"})]
        public virtual IIS.Probadesyat.РегистрВхода РегистрВхода
        {
            get
            {
                // *** Start programmer edit section *** (ВходГостя.РегистрВхода Get start)

                // *** End programmer edit section *** (ВходГостя.РегистрВхода Get start)
                IIS.Probadesyat.РегистрВхода result = this.fРегистрВхода;
                // *** Start programmer edit section *** (ВходГостя.РегистрВхода Get end)

                // *** End programmer edit section *** (ВходГостя.РегистрВхода Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВходГостя.РегистрВхода Set start)

                // *** End programmer edit section *** (ВходГостя.РегистрВхода Set start)
                this.fРегистрВхода = value;
                // *** Start programmer edit section *** (ВходГостя.РегистрВхода Set end)

                // *** End programmer edit section *** (ВходГостя.РегистрВхода Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВходГостяE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВходГостяE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВходГостяE", typeof(IIS.Probadesyat.ВходГостя));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ВходГостя.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfВходГостя CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfВходГостя CustomAttributes)
    public class DetailArrayOfВходГостя : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Probadesyat.DetailArrayOfВходГостя members)

        // *** End programmer edit section *** (IIS.Probadesyat.DetailArrayOfВходГостя members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ВходГостя by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ВходГостя.
        /// </summary>
        public DetailArrayOfВходГостя(IIS.Probadesyat.РегистрВхода fРегистрВхода) : 
                base(typeof(ВходГостя), ((ICSSoft.STORMNET.DataObject)(fРегистрВхода)))
        {
        }
        
        public IIS.Probadesyat.ВходГостя this[int index]
        {
            get
            {
                return ((IIS.Probadesyat.ВходГостя)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Probadesyat.ВходГостя dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
